services:
  app:
    image: 'auth-service:latest'
    build:
      context: .
    container_name: auth-service
    ports:
      - "8081:8081" 
    networks:
      default:
        ipv4_address: 172.19.0.2
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
networks:
  default:
    name: network_default_test
    external: true