version: '2'
services:
  app:
    image: 'user-service:latest'
    build:
      context: .
    container_name: user-service
    ports:
      - "8082:8082" 
    networks:
      default:
        ipv4_address: 172.18.0.3
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
networks:
  default:
    name: network_default_test
    external: true