services:
    fiware-frontend:
        container_name: fiware-frontend
        build:
            context: ./
            dockerfile: Dockerfile
        image: fiware-frontend:latest
        ports:
            - 8081:3000
        networks:
          default:
            ipv4_address: 172.19.0.4
        extra_hosts:
          - "host.docker.internal:host-gateway"

networks:
  default:
    name: fiware_default
    external: true
